name: Build project
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: docker
    name: Build
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4

      - uses: https://github.com/pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: https://github.com/actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Upload production-ready build files
        uses: https://github.com/actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist
